# Generated by Django 5.0.1 on 2024-06-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacherprofile_academic_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='school_name',
            new_name='assigned_school',
        ),
    ]
