# Generated by Django 5.1 on 2024-10-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0004_rename_school_name_schoolprofile_school_and_more'),
        ('teacher', '0002_rename_assigned_school_teacherprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to='customsettings.schoolprofile'),
        ),
    ]
