# Generated by Django 5.1 on 2024-10-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacherprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='on_medical_leave',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='on_vocational_leave',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Substitute', 'Substitute')], max_length=10, null=True),
        ),
    ]
