# Generated by Django 5.0.1 on 2024-06-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0007_gradelevel'),
        ('teacher', '0003_rename_school_name_teacherprofile_assigned_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='assigned_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to='district.district_school_registration'),
        ),
    ]
