# Generated by Django 5.0.1 on 2024-06-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0011_alter_classname_grd_level_delete_gradelevel'),
        ('teacher', '0004_alter_teacherprofile_assigned_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='base_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_subject_teacher_profiles', to='customsettings.schoolsubject'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects_taught',
            field=models.ManyToManyField(related_name='teacher_subjects', to='customsettings.schoolsubject'),
        ),
    ]
