# Generated by Django 5.0.1 on 2024-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0011_alter_classname_grd_level_delete_gradelevel'),
        ('student', '0003_alter_classroom_grd_level_and_more'),
        ('teacher', '0005_alter_teacherprofile_base_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='classes_taught',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher', to='student.classroom'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher_subjects', to='customsettings.schoolsubject'),
        ),
    ]
