# Generated by Django 5.0.1 on 2024-06-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0011_alter_classname_grd_level_delete_gradelevel'),
        ('teacher', '0006_alter_teacherprofile_classes_taught_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects_taught',
            field=models.ManyToManyField(related_name='teacher_subjects', to='customsettings.schoolsubject'),
        ),
    ]
