# Generated by Django 5.0.1 on 2024-06-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_classroom_grd_level_and_more'),
        ('teacher', '0007_alter_teacherprofile_subjects_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='classes_taught',
            field=models.ManyToManyField(related_name='teacher', to='student.classroom'),
        ),
    ]
