# Generated by Django 5.0.1 on 2024-06-30 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0011_alter_classname_grd_level_delete_gradelevel'),
        ('teacher', '0008_alter_teacherprofile_classes_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='base_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_subject_teacher_profiles', to='customsettings.schoolsubject'),
        ),
    ]
