# Generated by Django 5.0.6 on 2024-07-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprofile_subjects'),
        ('teacher', '0009_alter_teacherprofile_base_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_class', to='student.classroom'),
        ),
    ]
