# Generated by Django 5.0.1 on 2024-06-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0001_initial'),
        ('district', '0004_remove_schooladminprofile_school_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='school_admin',
            field=models.ManyToManyField(to='district.schooladminprofile'),
        ),
    ]
