# Generated by Django 5.0.1 on 2024-06-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0002_schoolprofile_school_admin'),
        ('district', '0004_remove_schooladminprofile_school_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_subject', models.ManyToManyField(to='district.subjects')),
            ],
        ),
    ]
