# Generated by Django 5.0.6 on 2024-12-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0004_rename_school_name_schoolprofile_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='twitter',
        ),
    ]
