# Generated by Django 5.0.1 on 2024-06-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0004_rename_shool_subjects_schoolprofile_school_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolsubject',
            old_name='school_subject',
            new_name='school_subjects',
        ),
    ]
