# Generated by Django 5.0.6 on 2024-12-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0005_remove_schoolprofile_facebook_and_more'),
        ('district', '0007_alter_district_school_registration_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='School_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schooladmin', to='district.district_school_registration'),
        ),
    ]
