# Generated by Django 5.0.1 on 2024-06-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0005_rename_school_subject_schoolsubject_school_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolsubject',
            old_name='school_subjects',
            new_name='subjects',
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_subjects',
            field=models.ManyToManyField(to='customsettings.schoolsubject'),
        ),
    ]
