# Generated by Django 5.0.1 on 2024-06-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0006_rename_school_subjects_schoolsubject_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='school_admin',
        ),
    ]
