# Generated by Django 5.0.1 on 2024-06-26 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0007_remove_schoolprofile_school_admin'),
        ('district', '0006_academiccalendar_holiday'),
        ('grading', '0002_alter_capture_academic_year'),
        ('student', '0002_alter_attendance_academic_year_alter_classroom_year_and_more'),
        ('teacher', '0002_alter_teacherprofile_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.academiccalendar'),
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='academic_calendar',
        ),
        migrations.DeleteModel(
            name='AcademicCalendar',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
