# Generated by Django 5.0.1 on 2024-06-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0008_alter_classname_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubject',
            name='schoolprofile_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customsettings.schoolprofile'),
        ),
    ]
