# Generated by Django 5.0.1 on 2024-06-28 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0009_schoolsubject_schoolprofile_name'),
        ('district', '0006_academiccalendar_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district_school_registration'),
        ),
    ]
