# Generated by Django 5.0.1 on 2024-06-28 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0010_alter_schoolprofile_school_name'),
        ('district', '0007_gradelevel'),
        ('student', '0003_alter_classroom_grd_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='grd_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.gradelevel'),
        ),
        migrations.DeleteModel(
            name='GradeLevel',
        ),
    ]
