# Generated by Django 5.0.6 on 2024-08-21 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customsettings', '0001_initial'),
        ('district', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('weekly', 'Weekly Exercise'), ('assignment', 'Assigment'), ('year', 'End-of-Year Exam')], max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('total_mark', models.IntegerField(default=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_captured', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.academiccalendar')),
                ('select_classes', models.ManyToManyField(to='student.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customsettings.schoolsubject')),
            ],
        ),
        migrations.CreateModel(
            name='CapturedClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captured', models.BooleanField(default=False)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.capture')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='GetMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveBigIntegerField(blank=True, null=True)),
                ('grade', models.PositiveBigIntegerField(blank=True, null=True)),
                ('pass_code', models.CharField(blank=True, default='F', max_length=1, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('captured_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grading.capturedclassroom')),
                ('student', models.ManyToManyField(related_name='marks', to='student.studentprofile')),
            ],
        ),
    ]
