# Generated by Django 5.1 on 2024-08-29 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='test_type',
            field=models.CharField(choices=[('weekly', 'Weekly Exercise'), ('assignment', 'Assignment'), ('year', 'End-of-Year Exam')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='getmark',
            name='student',
        ),
        migrations.AddField(
            model_name='getmark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='student.studentprofile'),
        ),
    ]
