# Generated by Django 5.1 on 2024-08-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_alter_capture_test_type_remove_getmark_student_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getmark',
            name='student',
        ),
        migrations.AddField(
            model_name='getmark',
            name='student',
            field=models.ManyToManyField(related_name='marks', to='student.studentprofile'),
        ),
    ]
