# Generated by Django 5.0.1 on 2024-07-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0011_alter_classname_grd_level_delete_gradelevel'),
        ('grading', '0002_alter_capture_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customsettings.schoolsubject'),
        ),
    ]
