# Generated by Django 5.1 on 2024-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_remove_getmark_student_getmark_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='test_type',
            field=models.CharField(choices=[('weekly', 'Weekly Exercise'), ('assignment', 'Assignment'), ('End of Term 1 Exam', 'End of Term 1 Exam'), ('End of Term 2 Exam', 'End of Term 2 Exam'), ('End of Term 3 Exam', 'End of Term 3 Exam'), ('End of Term 4 Exam', 'End of Term 4 Exam'), ('year', 'End-of-Year Exam')], max_length=50),
        ),
    ]
