# Generated by Django 5.0.1 on 2024-06-26 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0006_academiccalendar_holiday'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.academiccalendar'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.academiccalendar'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.academiccalendar'),
        ),
    ]
