# Generated by Django 5.1 on 2024-09-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_extracurricularactivity_studentprofile_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='photo',
            new_name='student_photo',
        ),
    ]
