# Generated by Django 5.0.1 on 2024-07-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0011_alter_classname_grd_level_delete_gradelevel'),
        ('student', '0003_alter_classroom_grd_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='subjects',
            field=models.ManyToManyField(to='customsettings.schoolsubject'),
        ),
    ]
