# Generated by Django 5.1 on 2024-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_photo_studentprofile_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_photo',
            field=models.ImageField(default='students_photos/default.jpg', upload_to='students_photos'),
        ),
    ]
