# Generated by Django 5.1 on 2024-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprofile_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='matriculated',
            field=models.BooleanField(default=False),
        ),
    ]
