# Generated by Django 5.1 on 2024-09-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentprofile_is_suspended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students_photos'),
        ),
    ]
