# Generated by Django 5.1 on 2024-09-14 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0002_extracurricularactivity'),
        ('student', '0006_alter_studentprofile_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='extra_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customsettings.extracurricularactivity'),
        ),
        migrations.DeleteModel(
            name='ExtraCurricularActivity',
        ),
    ]
