# Generated by Django 5.1 on 2024-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_extracurricularactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularactivity',
            name='participants',
            field=models.ManyToManyField(to='student.studentprofile'),
        ),
    ]
