# Generated by Django 5.1 on 2024-09-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_academiccalendar_term_4_end_date_and_more'),
        ('student', '0013_alter_classroom_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district_school_registration'),
        ),
    ]
