# Generated by Django 5.1 on 2024-09-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0003_district_school_registration_district'),
        ('student', '0014_alter_classroom_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='district.district_school_registration'),
        ),
    ]
