# Generated by Django 5.1 on 2024-10-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_academicrecord_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='school_name',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='school_name',
            new_name='school',
        ),
    ]
