# Generated by Django 5.1 on 2024-10-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0004_rename_school_name_schoolprofile_school_and_more'),
        ('student', '0017_rename_school_name_classroom_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customsettings.schoolprofile'),
        ),
    ]
