# Generated by Django 5.1 on 2024-10-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0004_rename_school_name_schoolprofile_school_and_more'),
        ('student', '0018_alter_classroom_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customsettings.schoolprofile'),
        ),
    ]
