# Generated by Django 5.0.6 on 2024-11-28 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0004_rename_school_name_schoolprofile_school_and_more'),
        ('student', '0019_alter_studentprofile_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchoolHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customsettings.schoolprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_history', to='student.studentprofile')),
            ],
        ),
    ]
