# Generated by Django 5.0.1 on 2024-06-18 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District_School_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='DistrictAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('admin', models.CharField(blank=True, choices=[('admin1', 'admin1'), ('admin2', 'admin2'), ('admin3', 'admin3')], max_length=10, null=True)),
                ('district_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='district_admin_profile', to=settings.AUTH_USER_MODEL)),
                ('district_schools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.district_school_registration')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('admin', models.CharField(blank=True, choices=[('admin1', 'admin1'), ('admin2', 'admin2'), ('admin3', 'admin3')], max_length=10, null=True)),
                ('assigned_school_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district_school_registration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
