# Generated by Django 5.0.1 on 2024-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladminprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
