# Generated by Django 5.1 on 2024-09-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_academiccalendar_term_4_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district_school_registration',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
