# Generated by Django 5.0.1 on 2024-06-18 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_alter_schooladminprofile_contact_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooladminprofile',
            old_name='user',
            new_name='school_admin',
        ),
        migrations.AddField(
            model_name='districtadminprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schooladminprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='districtadminprofile',
            name='district_schools',
        ),
        migrations.CreateModel(
            name='SchoolHeadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('assigned_school_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district_school_registration')),
                ('school_head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SchoolHead_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='districtadminprofile',
            name='district_schools',
            field=models.ManyToManyField(to='district.district_school_registration'),
        ),
    ]
