# Generated by Django 5.1 on 2024-10-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0003_district_school_registration_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district_school_registration',
            old_name='school_name',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='schooladminprofile',
            old_name='assigned_school_name',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='schoolheadprofile',
            old_name='assigned_school_name',
            new_name='school',
        ),
    ]
