# Generated by Django 5.0.1 on 2024-06-19 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0003_rename_user_schooladminprofile_school_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooladminprofile',
            name='school_admin',
        ),
        migrations.AddField(
            model_name='schooladminprofile',
            name='school_admin',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
