# Generated by Django 5.0.6 on 2024-11-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0004_rename_school_name_district_school_registration_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='academic_calendar',
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='holidays',
            field=models.ManyToManyField(related_name='academic_calendars', to='district.holiday'),
        ),
    ]
