# Generated by Django 5.0.1 on 2024-06-26 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0005_remove_schooladminprofile_school_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(blank=True, default=2024, null=True)),
                ('term_1_start_date', models.DateField(blank=True, null=True)),
                ('term_1_end_date', models.DateField(blank=True, null=True)),
                ('term_2_start_date', models.DateField(blank=True, null=True)),
                ('term_2_end_date', models.DateField(blank=True, null=True)),
                ('term_3_start_date', models.DateField(blank=True, null=True)),
                ('term_3_end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('academic_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='district.academiccalendar')),
            ],
        ),
    ]
