# Generated by Django 5.0.1 on 2024-06-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0006_academiccalendar_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(choices=[(8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
            ],
        ),
    ]
