# Generated by Django 5.0.6 on 2024-12-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0006_district_alter_district_school_registration_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district_school_registration',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district'),
        ),
    ]
