# Generated by Django 4.2 on 2024-08-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0007_gradelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtadminprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
